- name: Debug images to pull
  debug:
    var: docker_images

- name: Debug env
  debug:
   msg: "'{{ lookup('env', 'REGISTRY_URL') }}'

- name: Set variable folder_deployment
  set_fact:
    folder_deployment: "{{ ansible_env.HOME }}/deployment/{{ folder }}"

- name: 'Install docker dependencies'
  apt:
    name:
      - 'python3-pip'
    state: 'present'
    update_cache: yes
  become: yes
  become_user: "root"

- name: Install pip docker package for docker ansible api
  pip:
    name: docker-compose

- name: 'Log into private registry'
  community.docker.docker_login:
    registry: "{{ lookup('env', 'REGISTRY_URL') }}"
    username: "{{ lookup('env', 'REGISTRY_USER') }}"
    password: "{{ lookup('env', 'REGISTRY_PASS') }}"
    state: present

- name: Pull docker hub images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
    force_source: yes
  when: docker_hub_images is defined
  with_items: "{{ docker_hub_images }}"

- name: Pull image
  community.docker.docker_image:
    name: "{{ item }}:{{ tag }}"
    source: pull
    force_source: yes
  with_items: "{{ docker_images }}"
  when: docker_images is defined

- name: Create all network
  community.docker.docker_network:
    name: "{{ item }}"
  with_items: "{{ networks }}"
  when: networks is defined

- name: Create all volume
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items: "{{ volumes }}"
  when: volumes is defined

- name: Create folder
  file:
    path: "{{ folder_deployment }}"
    state: directory

- name: Copy compose file
  copy:
    src: "docker-compose.yml"
    dest: "{{ folder_deployment }}/docker-compose.yml"
  register: compose

- name: copy file to deployment folder
  ansible.posix.synchronize:
    src: files/build/
    dest: "{{ folder_deployment }}/files"
    checksum: yes
    delete: yes
    recursive: yes
    archive: no
  become: yes

- name: Recursive set 777 to all files
  file:
    path: "{{ item }}"
    mode: 0777
    recurse: yes
  with_items:
    - "{{ folder_deployment }}/files/storage"
    - "{{ folder_deployment }}/files/bootstrap/cache"
  become: yes

- name: Start docker compose
  community.docker.docker_compose:
    state: present
    project_src: "{{ folder_deployment }}"
    remove_orphans: yes

- name: migrate database
  community.docker.docker_container_exec:
    container: "{{ container }}"
    command: rails db:migrate

- name: Prune old artifacts images
  community.docker.docker_prune:
    images: yes
    images_filters:
      dangling: true
    networks: yes
    volumes: yes
