version: '3.6'

services:
  tracker_pg:
    image: postgres:alpine
    container_name: tracker_pg
    command: -c 'max_connections=500'
    restart: always
    ports:
      - "5500:5432"
    networks:
      - tracker_network
    volumes:
      - tracker_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: M4r1o53
      POSTGRES_HOST_AUTH_METHOD: "trust"

  tracker_redis:
    image: redis:alpine
    container_name: tracker_redis
    restart: always
    ports:
      - "6400:6379"
    networks:
      - tracker_network
    volumes:
      - tracker_redis_data:/data

  tracker_app:
    image: registry.victorsmits.com/twitchtracker/app:latest
    container_name: tracker_app
    environment:
      redis_url: redis://tracker_redis:6379
      SECRET_KEY_BASE: a075729f770dbb65262865954df73ab0afefe58ce5e993447d246184813d20cc02d19f35490598386699c5feab35f3fcbc9d3aced8cbe77e2faba8543ac20bd6
      pg_host: tracker_pg
    command: bundle exec rails s -p 3666 -b 0.0.0.0
    volumes:
      - .env:/rails/.env
    networks:
      - tracker_network
    depends_on:
      - tracker_pg
      - tracker_redis
    ports:
      - "3001:3666"
    stdin_open: true
    tty: true

  tracker_sidekiq:
    image: registry.victorsmits.com/twitchtracker/app:latest
    container_name: tracker_sidekiq
    volumes:
      - .env:/rails/.env
    networks:
      - tracker_network
    environment:
      redis_url: redis://tracker_redis:6379
      pg_host: tracker_pg
      SECRET_KEY_BASE: a075729f770dbb65262865954df73ab0afefe58ce5e993447d246184813d20cc02d19f35490598386699c5feab35f3fcbc9d3aced8cbe77e2faba8543ac20bd6
    command: sidekiq -c 6
    depends_on:
      - tracker_pg
      - tracker_redis
    stdin_open: true
    tty: true

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - .metabase-data:/metabase-data
    ports:
      - 9003:3000
    networks:
      - tracker_network

volumes:
  tracker_pg_data:
  tracker_redis_data:
  bundler_gems:
networks:
  tracker_network:
    external: true
