
x-common-steps: &common-steps
  - name: restore
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: https://minio.victorsmits.com
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      root: s3cache
      restore: true

  - name: bundle install
    image: ruby:3.2.3
    settings:
      mount:
        - ./bundle
    commands:
      - bundle config set path './bundle'
      - bundle config set without 'development'
      - bundle install

  - name: rebuild
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: https://minio.victorsmits.com
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      rebuild: true
      root: s3cache
      mount:
        - ./bundle
      when:
        event: push


---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  *common-steps
  - name: build docker
    image: plugins/docker
    settings:
      dockerfile: .drone/Dockerfile
      repo: registry.victorsmits.com/twitchtracker/app
      registry: registry.victorsmits.com
      tags: latest
      cache_from: registry.victorsmits.com/twitchtracker/app
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


---
kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: run ansible playbook production
    image: plugins/ansible
    environment:
      REGISTRY_URL:
        from_secret: docker_url
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
    settings:
      playbook: ../.ansible/deploy.yml
      inventory: ../.ansible/production.conf
      galaxy: ../.ansible/requirement.yml
      user: appli
      private_key:
        from_secret: ansible_private_key
