name: Build docker image

on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.victorsmits.com

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: twitchtracker/app:latest
          cache-from: type=registry,ref=twitchtracker/app:buildcache
          cache-to: type=registry,ref=twitchtracker/app:buildcache,mode=max
