name: Build docker image

on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore gem cache
        uses: tespkg/actions-cache/restore@v1
        with:
          endpoint: "minio.victorsmits.com" # optional, default s3.amazonaws.com
          accessKey: ${{ secrets.MINIO_ACCESS_KEY }}
          secretKey: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "s3cache" # required
          key: ${{ github.repository }}/${{ github.ref }}
          path: |
            Gemfile
            Gemfile.lock
            $PWD/vendor/bundle

      - name: install package
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            --no-install-recommends --fix-missing \
            ghostscript curl libgmp-dev nodejs wget locales less \
            build-essential git ca-certificates sudo ca-certificates \
            gnupg2 software-properties-common apt-transport-https lsb-release \
            postgresql-client-13 libpq-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Store gem cache
        uses: tespkg/actions-cache/save@v1
        with:
          endpoint: "minio.victorsmits.com"
          accessKey: ${{ secrets.MINIO_ACCESS_KEY }}
          secretKey: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "s3cache" # required
          key: ${{ github.repository }}/${{ github.ref }}
          path: |
            Gemfile
            Gemfile.lock
            $PWD/vendor/bundle

      - name: Log in to registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: registry.victorsmits.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.victorsmits.com/twitchtracker/app:latest
